kind: pipeline
name: archlinux

steps:
  - name: build
    image: ogarcia/archlinux
    privileged: true
    commands:
      - pacman -Sy --noconfirm archlinux-keyring
      - pacman -Syu --noconfirm make devtools
      - make rootfs
      - DOCKER_TAG=$$(date +%Y.%m.%d)
      - echo -n "$${DOCKER_TAG},latest" > .tags

  - name: push
    image: plugins/docker
    settings:
      repo: ogarcia/archtest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: notify
    image: drillster/drone-email
    from: drone@moire.org
    host:
      from_secret: email_host
    username:
      from_secret: email_username
    password:
      from_secret: email_password
    when:
      status:
        - failure
        - success
